---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-svc
spec:
  type: NodePort
  selector:
    app: sparkMasterApp
  ports:
    - name: spark-master-port
      protocol: TCP
      port: 7077
      targetPort: 7077
      nodePort: 30007
    - name: spark-gui-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008    
...
